[package]
name = "oven"
version = "0.2.13"
authors = ["XMPPwocky <nttheis@gmail.com>"]
repository = "https://github.com/XMPPwocky/oven"
description = "Simple cookie management for Iron"
license = "MIT"

[dependencies]
iron = "^0.2.2"
plugin = "^0.2.6"

[dependencies.cookie]
version = "^0.1.21"
features = ["secure"]
