[package]
name = "oven"
version = "0.1.3"
authors = ["XMPPwocky <nttheis@gmail.com>"]
repository = "https://github.com/XMPPwocky/oven"
description = "Simple cookie management for Iron"
license = "MIT"

[dependencies]
cookie = "^0.1.21"
iron = "^0.2.2"
